### ISSUE TITLE
Dispatcher thread issue, only on a headless VM, not in IDE?

### ISSUE THREAD

**Issue by davidwynter** [RuedigerMoeller/kontraktor#24]
SOLVED!

The error is a consequence of building an uberjar. I build a separate jar with all dependent jars in a lib sub directory and it ran fine.

Hi,

I have to test my Kontraktor based remote service that invokes a SOAP Service with a whitelist of IP addresses from a specific headless server so am not getting more than a stack trace. There are no classes in the stack trace from my code at all, so leaving me a little lost. I run this from Eclipse on my dev machine without issue, except it cannot access the SOAP server. Ideas?

`
admin@server-1:~$ java -cp example-client.jar uk.co.example.ExampleService example.properties
W 10:13:55:465 : DispatcherThread 1 : DispatcherThread : 
java.lang.ExceptionInInitializerError
    at org.xnio.Xnio.<clinit>(Xnio.java:93)
    at io.undertow.Undertow.start(Undertow.java:97)
    at org.nustaq.kontraktor.remoting.http.Http4K.getServer(Http4K.java:92)
    at org.nustaq.kontraktor.remoting.http.Http4K.getServer(Http4K.java:81)
    at org.nustaq.kontraktor.remoting.websockets.UndertowWebsocketServerConnector.getServer(UndertowWebsocketServerConnector.java:116)
    at org.nustaq.kontraktor.remoting.websockets.UndertowWebsocketServerConnector.connect(UndertowWebsocketServerConnector.java:60)
    at org.nustaq.kontraktor.remoting.base.ActorServer.start(ActorServer.java:80)
    at org.nustaq.kontraktor.remoting.websockets.WebSocketPublisher.lambda$publish$1(WebSocketPublisher.java:73)
    at org.nustaq.kontraktor.Actor.__submit(Actor.java:125)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.nustaq.kontraktor.impl.DispatcherThread.invoke(DispatcherThread.java:366)
    at org.nustaq.kontraktor.impl.DispatcherThread.pollQs(DispatcherThread.java:289)
    at org.nustaq.kontraktor.impl.DispatcherThread.pollQs(DispatcherThread.java:262)
    at org.nustaq.kontraktor.impl.DispatcherThread.run(DispatcherThread.java:162)
Caused by: java.lang.IllegalArgumentException: Invalid logger interface org.xnio._private.Messages (implementation not found in sun.misc.Launcher$AppClassLoader@5c647e05)
    at org.jboss.logging.Logger$1.run(Logger.java:2254)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.jboss.logging.Logger.getMessageLogger(Logger.java:2227)
    at org.jboss.logging.Logger.getMessageLogger(Logger.java:2214)
    at org.xnio._private.Messages.<clinit>(Messages.java:56)
    ... 17 more
`
The code excerpts

`
    public void init(String propspath) {

```
    // 1st argument is the name of the properties file
    Properties props = readProperties(propspath);
    password = (String) props.get("password");
    applicationName = (String) props.getProperty("applicationname");
    userName = (String) props.getProperty("username");

    // as websocket service, fast serialized
    // pass in the host IP address
    new WebSocketPublisher()
        .facade(service)
        .hostName(props.getProperty("hostname"))
        .urlPath("/service")
        .port(49001)
        .serType(SerializerType.FSTSer)
        .publish();
}
```

`

main method and service declaration:

`
    private static ExampleService service = null;

```
public static void main( String arg[] ) throws InterruptedException {
    service = Actor.AsActor(ExampleService.class);
    service.init(arg[0]);
}
```

`

**Comment by RuedigerMoeller** [comment]
hm .. seems to be an undertow related issue, maybe try upgrading the
dependency in the kontraktor pom ..

2016-03-23 11:20 GMT+01:00 davidwynter notifications@github.com:

**Comment by RuedigerMoeller** [comment]
even deeper than undertow: XNIO

2016-03-23 16:55 GMT+01:00 Rüdiger Möller moru0011@gmail.com:

**Comment by davidwynter** [comment]
I updated to undertow 1.2.11.Final

3 tests failed, not sure they are related to the change in version though

```
   ` <dependency>
        <groupId>io.undertow</groupId>
        <artifactId>undertow-core</artifactId>
        <version>1.2.11.Final</version>
    </dependency>

    <dependency>
        <groupId>io.undertow</groupId>
        <artifactId>undertow-websockets-jsr</artifactId>
        <version>1.2.11.Final</version>
    </dependency>`
```

`Failed tests:   testBlockEx(kontraktor.BasicTest)
  startStop(kontraktor.LifeCycleTest)
  test(kontraktor.TicketMachineTest)`

`-------------------------------------------------------------------------------`
`Test set: kontraktor.BasicTest`
`-------------------------------------------------------------------------------`
`Tests run: 18, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 32.691 sec <<< FAILURE!
testBlockEx(kontraktor.BasicTest)  Time elapsed: 2.022 sec  <<< FAILURE!
java.lang.AssertionError
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertTrue(Assert.java:52)
    at kontraktor.BasicTest.testBlockEx(BasicTest.java:625)`

This has nothing to do with the WebSocket, consistently fails though.

The startStop test is sensitive to timing. I ran it multiple times, it fails sometimes and not other. If I single step it, it failed.

TicketMachineTest (damn it takes a long time to run) also has  no relation to undertow so assume it is not the problem. It too is time sensitive, run in isolation from the IDE it passed.

`test(kontraktor.TicketMachineTest)  Time elapsed: 6.917 sec  <<< FAILURE!
java.lang.AssertionError
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertTrue(Assert.java:52)
    at kontraktor.TicketMachineTest.test(TicketMachineTest.java:90)`

I saw this too 
`org.nustaq.kontraktor.KTimeoutException: Timeout
    at org.nustaq.kontraktor.Promise.awaitHelper(Promise.java:450)
    at org.nustaq.kontraktor.Promise.await(Promise.java:392)
    at kontraktor.GeneratorTest.lambda$test$0(GeneratorTest.java:67)
    at kontraktor.GeneratorTest.test(GeneratorTest.java:77)`

and 

`org.nustaq.kontraktor.KTimeoutException: Timeout
    at org.nustaq.kontraktor.Promise.awaitHelper(Promise.java:450)
    at org.nustaq.kontraktor.Promise.await(Promise.java:392)
    at kontraktor.GeneratorTest.test(GeneratorTest.java:50)`

I'll build without tests and try that

**Comment by davidwynter** [comment]
SOLVED, for those that skip to the last message. Cannot build an uberjar, it runs fine as separate jars files, with dependent jars in a lib subdirectory and the main jar manifest adding them to the classpath.

Just spotted this, with an uberjar build

`[INFO] Minimizing jar uk.co.example:exampleservice:jar:0.0.1-SNAPSHOT
[WARNING] jboss-websocket-api_1.1_spec-1.1.0.Final.jar, javax.websocket-api-1.1.jar define 43 overlapping classes: 
[WARNING]   - javax.websocket.Decoder$Text
[WARNING]   - javax.websocket.DeploymentException
[WARNING]   - javax.websocket.SendHandler
[WARNING]   - javax.websocket.ClientEndpointConfig
[WARNING]   - javax.websocket.SendResult
[WARNING]   - javax.websocket.Extension
[WARNING]   - javax.websocket.ClientEndpointConfig$Builder
[WARNING]   - javax.websocket.OnError
[WARNING]   - javax.websocket.Decoder
[WARNING]   - javax.websocket.Encoder$BinaryStream
[WARNING]   - 33 more...`

Further inspection shows that it looks like undertow switched websocket-api implementation

So I updated kontraktor-http to use org.jboss.spec.javax.websocket:jboss-websocket-api_1.1_spec:jar:1.1.1.Final as does undertow. Ran the tests (all passed until I got an OOM) deployed to my server and got exactly the same exception. I'll have a look at the actual exception now and see if I can find out why it occurs

**Comment by RuedigerMoeller** [comment]
oops, missed your valuable input. I am aware the test suite is timing dependent, I admit using these as a playground for the most part ;). As kontraktor is used at least in 2 midsize to large systems, there is some reasonable end to end test coverage though.

**Comment by RuedigerMoeller** [comment]
as for oom in remoting, if remote promises or callbacks are kept unfulfilled/closed, its callback id entry is not removed, so (remote) promises  always need to be either resolved or rejected. same happens if sender floods a remote actor (queuing until oom), this behaviour might happen now as kontraktor moved to unbounded queues with 3.16, but test cases have been created with older bounded queue versions
