### ISSUE TITLE
Http4K initialization exception

### ISSUE THREAD

**Issue by davidwynter** [RuedigerMoeller/kontraktor#37]
Hi,

I am using the kontraktor-http module with this initialization

    		BldFourK bld4k = Http4K.Build(thisWebappIP, port).fileRoot("/", root).fileRoot("/jsk", jsroot)
				.httpAPI("/api", csHttpApp).serType(SerializerType.JsonNoRef).setSessionTimeout(30_000)
				.build()
				.websocket("/ws", csHttpApp).serType(SerializerType.JsonNoRef)
				.build().build();

I am getting this exception:

    Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.xnio.Xnio.<clinit>(Xnio.java:93)
	at io.undertow.Undertow.start(Undertow.java:97)
	at org.nustaq.kontraktor.remoting.http.Http4K.getServer(Http4K.java:94)
	at org.nustaq.kontraktor.remoting.http.builder.BldFourK.build(BldFourK.java:115)
	at uk.co.example.quokka.Main.main(Main.java:68)
    Caused by: java.lang.IllegalArgumentException: Invalid logger interface org.xnio._private.Messages (implementation not found in sun.misc.Launcher$AppClassLoader@6bc7c054)
	at org.jboss.logging.Logger$1.run(Logger.java:2254)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.jboss.logging.Logger.getMessageLogger(Logger.java:2227)
	at org.jboss.logging.Logger.getMessageLogger(Logger.java:2214)
	at org.xnio._private.Messages.<clinit>(Messages.java:56)
	... 5 more

Where the line 68 in my Main class is as above. 

I tried to trace the error, but kontraktor-http 3.28 is using undertow 1.2.8.Final which uses xnio 3.3.1.Final, the code that causes the problem is below, the final line is Xnio.java:93. But I cannot understand the error.

    static {
        boolean nio2 = false;
        try {
            // try to find an NIO.2 interface on the system class path
            Class.forName("java.nio.channels.MulticastChannel", false, null);
            nio2 = true;
        } catch (Throwable t) {
        }
        NIO2 = nio2;
        msg.greeting(Version.VERSION); 

I'll fork kontraktor and try newer versions of undertow to see if I can resolve this, otherwise Ideas?

**Comment by davidwynter** [comment]
This is a packaging issue, I use maven-shade-plugin which is causing the error by omitting a class. When I removed the minimizeJar == true directive it fixed this problem. Worth knowing.
