### ISSUE TITLE
WebSocketConnectable throws IOException not available in catch

### ISSUE THREAD

**Issue by davidwynter** [RuedigerMoeller/kontraktor#59]
I have this code:

`
	CSHttpApp csHttpService = null;

	try {	

		csHttpService = (CSHttpApp) initiconnectable
					.connect((res, err) -> logger.error(initiconnectable + " not connected!")).await();

		csHttpService.setHostAddress(cshostname);

	} catch(AwaitException ae) {

		String errMsg = "Service " + cshostname + " has exception connecting to the Failover main service - " + ae.getMessage() + "\n";

		logger.error(errMsg);

		notStarted.add(errMsg);

	}
`

If the csHttpService is not available then it throws an exception that I cannot add a catch statement for, "Unreachable catch block"

`
    java.lang.RuntimeException: java.io.IOException: UT003035: Connection timed out
	at org.nustaq.kontraktor.remoting.websockets.JSR356ClientConnector$WSClientEndpoint.<init>(JSR356ClientConnector.java:105)
	at org.nustaq.kontraktor.remoting.websockets.JSR356ClientConnector.connect(JSR356ClientConnector.java:73)
	at org.nustaq.kontraktor.remoting.base.ActorClient.connect(ActorClient.java:72)
	at org.nustaq.kontraktor.remoting.websockets.WebSocketConnectable.lambda$connect$0(WebSocketConnectable.java:69)
	at org.nustaq.kontraktor.remoting.websockets.WebSocketConnectable.connect(WebSocketConnectable.java:80)
	at org.nustaq.kontraktor.remoting.base.ConnectableActor.connect(ConnectableActor.java:50)
	at uk.co.example.quokka.InitServicesHelper.initFailoverApps(InitServicesHelper.java:175)
`

I'd prefer to catch it.

**Comment by RuedigerMoeller** [comment]
hum :) .. 
AFAIk in this scenario it can be signaled back via rejecting a promise only. As sloppy programming frequently does ignore async errors `(result,error) -> if ( result != null ) ..` diagnostics with cluster startup failures was hard, so I forced dumping of those :).

will address with one of the next minor releases
